innovation_tracker/blog/urls.py
from django.conf.urls import url
from .views import (
    CreatePost,
    DetailPost,
    DraftPosts,
    UpdatePost,
    DeletePost,
    post_publish,
    add_comment,
    vote_post,
)

app_name = 'blog'
urlpatterns = [
    url(r'posts/(?P<pk>\d+)/publish/$',post_publish,name='post_publish'),
    url(r'^create/$',CreatePost.as_view(),name='create'),
    url(r'^detail/(?P<pk>\d+)/$',DetailPost.as_view(),name='detail'),
    url(r'^drafts/$',DraftPosts.as_view(),name='draft'),
    url(r'^update/(?P<pk>\d+)/$',UpdatePost.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',DeletePost.as_view(),name='delete'),
    url(r'^post/(?P<pk>\d+)/comment/$', add_comment, name='add_comment'),
    url(r'^post/(?P<pk>\d+)/vote/(?P<vote_type>\-?\d+)/$', vote_post, name='vote_post'),
]

innovation_tracker/mysite/urls.py
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url,include
from blog.views import (
    sign_up,
    log_out,
    log_in,
    ListPosts,
)

urlpatterns = [
    url(r'^$',ListPosts.as_view(),name='posts'),
    url(r'^blog/',include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^sign_up/$',sign_up,name='sign_up'),
    url(r'^login/$',log_in,name='log_in'),
    url(r'logout/$',log_out,name='log_out'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

innovation_tracker/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.TextField()
    category = models.CharField(max_length=120)
    image = models.ImageField(upload_to='posts',blank=True,null=True)
    content = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True,null=True)

    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"pk": self.pk})
    
    def total_upvotes(self):
        return self.votes.filter(vote=1).count()

    def total_downvotes(self):
        return self.votes.filter(vote=-1).count()

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    comment = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.author.username
    
class Vote(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='votes')
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    vote = models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])  # Change from TextField to IntegerField
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{} - {}".format(self.author.username, self.get_vote_display())
    
    

    

innovation_tracker/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('title','content', 'category','image')
        labels = {
            'title':'Title',
            'category':'Category',
            'content':'Content',
            'image':'Image (Optional)'
        }
        widgets = {
            'title': forms.Textarea(attrs={'class':'form-control','id':"exampleFormControlTextarea1", 'rows':"2",'placeholder':'Type Your Title Here'}),
            'content': forms.Textarea(attrs={'class':'form-control','id':"exampleFormControlTextarea1", 'rows':"20",'placeholder':'Type Your Text Here ...'}),
            'category': forms.TextInput(attrs={'class':'form-control','placeholder':'Type Your category Here ...'}),
            'image':forms.ClearableFileInput(attrs={'class':'form-control', 'type':'file', 'id':'formFile'})
        }

class SignUpForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ('username','email','password')
        labels = {
            'username':'',
            'password':'',
            'email':'',
        }

        widgets = {
            'username':forms.TextInput(attrs={
                'placeholder':'Type your username here',
                'class':'field',
            }),
            'email':forms.EmailInput(attrs={
                'placeholder':'example@email.com',
                'class':'field',
            }),
            'password':forms.PasswordInput(attrs={
                'placeholder':'Type your password here',
                'class':'field password',
            }),
        }

        help_texts = {
            'username':None,
        }

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('comment',)
        labels = {
            'comment':''
        }
        widgets = {
            'comment': forms.Textarea(attrs={'class':'form-control','id':"exampleFormControlTextarea1", 'rows':"3", 'placeholder':'Type Your Comment Here...'})
        }

innovation_tracker/blog/views.py
from django.shortcuts import render, get_list_or_404,redirect,HttpResponse,HttpResponseRedirect, get_object_or_404
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post, Comment, Vote
from django.views.generic import DetailView
from .forms import PostForm,SignUpForm, CommentForm
from django.urls import reverse_lazy,reverse
from django.views.generic import (
    TemplateView, CreateView,
    ListView,DetailView,
    UpdateView,DeleteView,
)

class ListPosts(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/list_posts.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class CreatePost(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_form.html'
    model = Post
    form_class = PostForm
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['value'] = 'Create'
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

class DetailPost(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        post = self.get_object()

        # Get user's vote status
        if user.is_authenticated:
            vote = Vote.objects.filter(post=post, author=user).first()
            context['user_vote'] = vote.vote if vote else None
        else:
            context['user_vote'] = None  # Not logged in

        # Add upvote/downvote count
        context['total_upvotes'] = post.total_upvotes()
        context['total_downvotes'] = post.total_downvotes()

        # Add comment form to context
        context['comment_form'] = CommentForm()

        return context


class DraftPosts(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/draft_posts.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by("created_date")

class UpdatePost(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    model = Post
    form_class = PostForm

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['value'] = 'Update'
        return context

class DeletePost(LoginRequiredMixin,DeleteView):
    login_url = '/login/'
    model = Post
    template_name = 'blog/confirm_delete.html'
    context_object_name = 'post'
    success_url = reverse_lazy('posts')


@login_required(login_url='/login/')
def post_publish(request,pk):
    post = get_list_or_404(Post,pk=pk)[0]
    post.publish()
    return redirect('blog:detail',pk=pk)

############# login_signup #############

def sign_up(request):
    registered = False

    if request.method == 'POST':
        user_form = SignUpForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        
        else:
            print(user_form.errors)
    else:
        user_form = SignUpForm()   
    return render(request,'blog/auth/signup.html',{'user_form': user_form,
                                                          'registered': registered
                                                          })
                                                          
def log_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)

        if user is not None:
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('posts')
        else:
            return HttpResponse("Invalid Username or Password ..")
    return render(request,'blog/auth/login.html',{})
        
@login_required
def log_out(request):
    logout(request)
    return redirect('posts')
        
@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('blog:detail', pk=post.pk)  # Ensure this matches 'detail' in your URLs

    return redirect('blog:detail', pk=post.pk)


@login_required
def vote_post(request, pk, vote_type):
    post = get_object_or_404(Post, pk=pk)
    existing_vote = Vote.objects.filter(post=post, author=request.user).first()

    if existing_vote:
        if existing_vote.vote == vote_type:
            existing_vote.delete()  # Remove vote if clicking the same button again
        else:
            existing_vote.vote = vote_type  # Change vote type
            existing_vote.save()
    else:
        Vote.objects.create(post=post, author=request.user, vote=vote_type)

    return redirect('blog:detail', pk=pk)

innovation_tracker/blog/templates/blog/confirm_delete.html
{% extends 'blog/post_base.html' %}
    {% block title %}
        Remove | {{ post.title }}
    {% endblock %} 
    {% block content %}
    <div class="delete">
        <form method="POST">
            {% csrf_token %}
            <h3>Delete {{ post.title|title }} Post</h3>
            <p>Are you Sure you want to delete this post?</p>
            <div class="delete-action">
                <input class="button" type="submit" value="Confirm">
                <a class="button" href="{% url 'blog:detail' pk=post.pk %}">Cancel</a>
            </div>
        </form>
    </div>
    {% endblock %} 

innovation_tracker/blog/templates/blog/draft_posts.html
{% extends 'blog/post_base.html' %}
    {% block title %}
        Unpublished Posts | Drafts
    {% endblock %} 
    {% block content %}
        {% for post in posts %}
        <div class="post">
            <h3><a href="{% url 'blog:detail' pk=post.pk %}">{{ post.title|title }}</a></h3>
            <p class="date"><small>created on: {{ post.created_date|date:'d-m-Y' }}</small></p>
            <p class="content">{{ post.content|truncatechars:70 }}</p>
        </div>
        {% endfor %}
    {% endblock %} 

innovation_tracker/blog/templates/blog/list_posts.html
{% extends 'blog/post_base.html' %}
{% block title %}
    Unpublished Posts | Drafts
{% endblock %} 
{% block content %}
    <section class="explore-section section-padding">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                    <h2 class="mb-4">Browse Ideas</h2>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                {% for post in posts %}
                    {% if forloop.counter0|divisibleby:3 %}
                        </div><div class="row"> {# Start a new row every 3 posts #}
                    {% endif %}

                    <div class="col-lg-4 col-md-6 col-12 mb-4">
                        <div class="custom-block bg-white shadow-lg">
                            <a href="{% url 'blog:detail' pk=post.pk %}">
                                <div class="d-flex">
                                    <div>
                                        <h5 class="mb-2">{{ post.title|title }}</h5>
                                        <p class="mb-0">{{ post.content|truncatechars:200 }}</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div> 
        </div>
    </section>
{% endblock %}

innovation_tracker/blog/templates/blog/post_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/login.css" %}">
    <link rel="stylesheet" href="{% static "css/signup.css" %}">
    <link rel="stylesheet" href="{% static "css/list.css" %}">
    <link rel="stylesheet" href="{% static "css/detail.css" %}">
    <link rel="stylesheet" href="{% static "css/comments.css" %}">
    <link rel="stylesheet" href="{% static "css/form.css" %}">
    <link rel="stylesheet" href="{% static "css/delete.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/topic_listing.css" %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="nav-1">
            <p ><a style="color: white;" href="{% url 'posts' %}">Innovation Club</a></p>
            <nav>
                <ul>
                    <li><a href="{% url 'posts' %}">Home</a></li>
                </ul>
            </nav>
        </div>
        <div class="nav-2">
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'blog:create' %}">New Post</a></li>
                        <li><a href="{% url 'blog:draft' %}">Drafts</a></li>
                        <li><a href="#">{{ user.username }}</a></li>
                        <li><a class='btn btn-primary' type = 'button' href="{% url 'log_out' %}">Sign out</a></li>
                    {% else %}
                        <li><a class='btn btn-secondary' type = 'button' href="{% url "sign_up" %}">Sign up</a></li>
                        <li><a class='btn btn-primary' type = 'button' href="{% url "log_in" %}">Sign in</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        
    </header>
    <div class="container">
        {% block content %}
        {% endblock %}  
    </div>
     
</body>
</html>

innovation_tracker/blog/templates/blog/post_detail.html
{% extends 'blog/post_base.html' %}
    {% load static %}
    {% block title %}
        {{ post.title }}
    {% endblock %} 
    {% block content %}
        <div class="container-sm">
            <div>
                {% if post.image %}
                    <img src="{{ post.image.url }}" alt="not found!!" class="post-image">
                {% endif %}
                <h2>{{ post.title|title }}</h2>
                <p class="date"><small>Published by <em><strong>{{ post.author }}</strong></em>, on {{ post.published_date|date:'d-m-Y, h:m:s' }}, Category: <em><strong>{{ post.category }}</strong></em></small></p>
                <p class="content">{{ post.content|linebreaksbr }}</p>
            </div>
            <div class="d-flex bd-highlight mb-3">
                <div class="me-auto p-2 bd-highlight">
                    {% if user.is_authenticated %}
                        {% if request.user == post.author %}
                            <div class="row">
                                <div class="d-grid gap-2 d-md-block">
                                    {% if not post.published_date %}
                                        <a class="btn btn-primary" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
                                    {% endif %}
                                    <a class="btn btn-primary" href="{% url 'blog:update' pk=post.pk %}">Edit</a>
                                    <a class="btn btn-danger" href="{% url 'blog:delete' pk=post.pk %}">Remove</a>                                   
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
                <div class="ms-auto p-2 bd-highlight">
                    {% if not post.published_date %}
                    {% else %}
                    {% if user.is_authenticated %}
                        <form action="{% url 'blog:vote_post' post.pk 1 %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button class="btn btn-secondary" type="submit" {% if user_vote == 1 %} style="background-color: #198754;"{% endif %}>
                                ({{ total_upvotes }}) Upvote 👍
                            </button>
                            </form>
        
                            <form action="{% url 'blog:vote_post' post.pk -1 %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button class="btn btn-secondary" type="submit" {% if user_vote == -1 %} style="background-color: #dc3545;"{% endif %}>
                                ({{ total_downvotes }}) Downvote 👎
                            </button>
                        </form>
                    {% else %}

                        <button class="btn btn-secondary" type="button" disabled>
                                ({{ total_upvotes }}) Upvote 👍
                        </button>
        

                        <button class="btn btn-secondary" type="button" disabled>
                                ({{ total_downvotes }}) Downvote 👎
                        </button>
                            
                    {% endif %}
                    {% endif %}
            </div>
            
        </div>
        {% if not post.published_date %}
        {% else %}
        <div class="comments">
            <hr>
            <h4><i>Comments:</i></h4>
            {% for comment in post.comments.all %}
                <div class="containter">
                    <div class="author">
                        <img src="{% static 'images/user-icon.png' %}" alt="">
                        <div class="author-name">
                            <p class="name">{{ comment.author }}</p>
                            <small>{{ comment.created_date|date:'M d,Y, h:m:s' }}</small>
                        </div>    
                    </div>
                        <p class="comment">{{ comment.comment|linebreaksbr }}</p>
                </div>
                {% empty %}
                <p class="no-cmnt"><i>no comments ...</i></p>
            {% endfor %}
            <div class="create">
                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'blog:add_comment' post.pk %}">
                        {% csrf_token %}
                        {{ comment_form.as_p }}
                        <div class="d-grid gap-2">
                            <button class="btn btn-primary" type="submit">Submit your comment</button>
                        </div>
                    </form>
                {% else %}
                    <p class="alert alert-warning">You must be logged in to comment or vote.</p>
                    <a type='button' class="btn btn-primary" href="{% url 'log_in' %}">Log in to Comment or vote</a>
                {% endif %}
            </div>
        </div>
        {% endif %}    
    {% endblock %} 

innovation_tracker/blog/templates/blog/post_form.html
{% extends 'blog/post_base.html' %}
    {% block title %}
        create
    {% endblock %} 
    {% block content %}
    <div class="container-sm">
        <div class="">
            <h3>{{ value }} Post</h3>
            <form method="POST" enctype="multipart/form-data" style="display: inline">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="d-grid gap-2"></div>
                    <button class="btn btn-primary" type="submit">{{ value }} post</button>
                </div>
            </form>
        </div>
    </div>
    
    {% endblock %} 

innovation_tracker/blog/templates/blog/user_posts.html
{% extends 'blog/post_base.html' %}
    {% block title %}
        Unpublished Posts | Drafts
    {% endblock %} 
    {% block content %}
        {% for post in posts %}
            {% if request.user == post.author %}
                <div class="post">
                    <h3><a href="{% url 'blog:detail' pk=post.pk %}">{{ post.title|title }}</a></h3>
                    <p class="date"><small>{{ post.published_date|date:'d-m-Y, h:m:s' }}, by {{ post.author }}</small></p>
                    <p class="content">{{ post.content|truncatechars:70 }}</p>
                </div>
            {% endif %}    
        {% endfor %}
    {% endblock %}